# site information
authors: "Ariel Waldman and Lisa Ballard"
description: "A catalog of the active human-made machines that freckle our solar system and dot our galaxy."
twitter: spaceprob_es
sticker_url: https://www.stickermule.com/user/1070646893/stickers
poster_url: http://society6.com/product/space-probes_print

# jekyll stuff:
markdown: kramdown
permalink: /:title/
exclude: [README.markdown, Makefile, vendor]
timezone: UTC
encoding: utf-8
baseurl: /
exclude_from_localizations: []
languages: ["en","tr"]
include: ["_redirect"]
